export const types = {
  FETCH_ROVERS_BY_MODEL_REQUEST: 'FETCH_ROVERS_BY_MODEL_REQUEST',
  FETCH_ROVERS_BY_MODEL_SUCCESS: 'FETCH_ROVERS_BY_MODEL_SUCCESS',
  FETCH_ROVERS_BY_MODEL_FAILURE: 'FETCH_ROVERS_BY_MODEL_FAILURE',
};
